-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 20:35:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assignment1_scenario1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment1_scenario1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment1_scenario1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assignment1_scenario1` ;

-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Customer` (
  `Customer_ID` INT NOT NULL,
  `Customer_Name` VARCHAR(50) NOT NULL,
  `Shipping_Address` VARCHAR(50) NULL,
  `Mailing_Address` VARCHAR(50) NOT NULL,
  `Phone_Number` VARCHAR(50) NOT NULL,
  `Credit_Limit` VARCHAR(50) NOT NULL,
  `Discount` VARCHAR(50) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Company` (
  `Company_Name` INT NOT NULL,
  `Company_Address` VARCHAR(50) NOT NULL,
  `Company_Phone` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Company_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Order` (
  `Order_Number` INT NOT NULL,
  `Order_Date` VARCHAR(50) NOT NULL,
  `Order_Quantity` VARCHAR(50) NOT NULL,
  `Customer_Customer_ID` INT NOT NULL,
  `Company_Company_Name` INT NOT NULL,
  PRIMARY KEY (`Order_Number`),
  INDEX `fk_Order_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  INDEX `fk_Order_Company1_idx` (`Company_Company_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `assignment1_scenario1`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Company1`
    FOREIGN KEY (`Company_Company_Name`)
    REFERENCES `assignment1_scenario1`.`Company` (`Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Product` (
  `Product_Code` INT NOT NULL,
  `Product_Description` VARCHAR(50) NULL,
  `Quantity_On_Hand` VARCHAR(50) NOT NULL,
  `Quantity_Backordered` VARCHAR(50) NOT NULL,
  `Standard_Price` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Product_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Part` (
  `Part_Number` INT NOT NULL,
  `Part_Description` VARCHAR(50) NULL,
  PRIMARY KEY (`Part_Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Order_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Order_has_Product` (
  `Order_Order_Number` INT NOT NULL,
  `Product_Product_Code` INT NOT NULL,
  `Product_Backordered` VARCHAR(50) NOT NULL,
  `Product_Filled` VARCHAR(50) NOT NULL,
  INDEX `fk_Order_has_Product_Product1_idx` (`Product_Product_Code` ASC) VISIBLE,
  INDEX `fk_Order_has_Product_Order_idx` (`Order_Order_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Product_Order`
    FOREIGN KEY (`Order_Order_Number`)
    REFERENCES `assignment1_scenario1`.`Order` (`Order_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Product1`
    FOREIGN KEY (`Product_Product_Code`)
    REFERENCES `assignment1_scenario1`.`Product` (`Product_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1_scenario1`.`Product_has_Part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1_scenario1`.`Product_has_Part` (
  `Product_Product_Code` INT NOT NULL,
  `Part_Part_Number` INT NOT NULL,
  `Part_Quantity_Required` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Product_Product_Code`, `Part_Part_Number`),
  INDEX `fk_Product_has_Part_Part1_idx` (`Part_Part_Number` ASC) VISIBLE,
  INDEX `fk_Product_has_Part_Product1_idx` (`Product_Product_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Part_Product1`
    FOREIGN KEY (`Product_Product_Code`)
    REFERENCES `assignment1_scenario1`.`Product` (`Product_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Part_Part1`
    FOREIGN KEY (`Part_Part_Number`)
    REFERENCES `assignment1_scenario1`.`Part` (`Part_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
